# The East Wing Config

title: The East Wing
email: tim@theeastwing.net
description: A show about the people who build the web.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock', '.asset-cache']
timezone: America/Chicago
permalink: /episodes/:title/

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/stylesheets
  style: :compressed

# Markdown Rendering
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md,mdown

kramdown:
  input: GFM

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
